### ISSUE TITLE
DisplayMessage procedure in GAME.PAS uses Time instead of time

### ISSUE THREAD

**Issue by TigerLeep** [asiekierka/reconstruction-of-zzt#5]
I've been pouring over this source pretty intently (working on a C# port/recreation), and I noticed in the `DisplayMessage` procedure in `GAME.PAS`, it receives a variable named `time`, but uses `Time` in the body of the procedure.  Pascal has a `Time` function, which threw me for a loop at first.  I'm assuming that, since Pascal is not case-sensitive, the `Time` in the body of `DisplayMessage` actually refers to the `time` parameter passed to it, and not the `Time` function from Pascal.  I'm guessing that the same-named variable "overrides" or "hides" the Pascal Time function.

Is the use of `Time` instead of `time` in the body of the `DisplayMessage` procedure a mistake?

**Comment by asiekierka** [comment]
Pascal is not case-sensitive. This allowed the typo to persist; it was a mistake and has now been fixed and made less confusing.
